### ISSUE TITLE
Position of TP makings in Camps and Locations area

### ISSUE THREAD

**Issue by Titoo8899** [AustereTony-MCMods/Oxygen-Teleportation#1]
Hi,
then I make a TP Position and in a other area a second will I the Positions of makin in 1,2,3... have.
But in your mod is this other. I have .... 3,2,1
![2019-03-31_12 39 27](https://user-images.githubusercontent.com/42325138/55288070-7db7ea80-53b2-11e9-97f6-a2167b4ea657.png)
![2019-03-31_12 39 29](https://user-images.githubusercontent.com/42325138/55288071-7db7ea80-53b2-11e9-8d10-f040c49b19da.png)

Please make  switched added

**Comment by AustereTony-MCMods** [comment]
Added sort buttons in ver. 0.1.2a. Please, check and report here.

**Comment by Titoo8899** [comment]
hi,
your sort button update work, but I have found 2 thinks what you must fix or adding in the next versions.

1. The sort button reset by close your tp menü and new open of your tp menü and we have the old sort of the camp / locations tps. Please fix this.

2. The sort button is good but then you can add that a tp what we have create per click up or down sort  find I it good. I have 3 tp points but I will the 2 tp point on first position place. And with the sort can I only the 1 Positon of the 3 make and the 3 to the 1 Position. Please add a up and down sort function for the middle TP points.

**Comment by AustereTony-MCMods** [comment]
Sorry for late answer. Well. I will add advanced sorting with custom layouts, but in the future, because this is not vital now.

**Comment by Titoo8899** [comment]
Thanks the sort button works so fine, thanks.
