### ISSUE TITLE
Menu doesn't show up on Server

### ISSUE THREAD

**Issue by AngelusQQ** [AustereTony-MCMods/Oxygen-Teleportation#2]
With the latest update 0.9, the teleportation menu doesn't show up when on a server.
Works fine in single player. 

Error Message: https://pastebin.com/Dtzbm8fG

I already checked my configs, image width and height were set to default values (800, 450) for both client and server.

No rush on this (for me at least), just reporting.

**Comment by AustereTony-MCMods** [comment]
Hello.
I don’t know what could be the problem. Try to delete all the config files and check server again. If the problem persists, try to remove all modifications except Oxygen modules and check again, maybe something is conflicting with it.

**Comment by AngelusQQ** [comment]
Okay thanks, I didn't get a chance to try removing all modifications but I suspect its something with spongeforge if its working on a regular forge server.

I will try when I get home, but even if nothing can be done not the end of the world. I was just trying the mod because the concept & design looks amazing. I currently don't have a use case for this mod as of now, but thanks anyway!
